!SESSION 2018-01-08 10:10:48.712 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_92
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=zh_CN
Command-line arguments:  -os win32 -ws win32 -arch x86

This is a continuation of log file D:\WorkSpace\MyCode\GE_EFM8LB12F64E-B-QFN32_YJ\.metadata\.bak_0.log
Created Time: 2018-01-08 15:55:20.686

!ENTRY com.silabs.ss.platform.content.core 1 0 2018-01-08 15:55:20.687
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
!STACK 0
java.lang.Exception: /efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json is not currently available offline.  Please make sure you have Internet access.
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:378)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.framework.debugger.core 4 0 2018-01-08 15:55:20.688
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Asset error while getting device descriptor(s) for agent
	at com.silabs.ss.platform.api.rcp.core.StatusReporter.newCoreException(StatusReporter.java:239)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:63)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	... 14 more
!SUBENTRY 1 com.silabs.ss.framework.debugger.tcf.agent 4 0 2018-01-08 15:55:20.689
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
!SUBENTRY 2 com.silabs.ss.platform.content.core 2 0 2018-01-08 15:55:20.689
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY com.silabs.ss.platform.content.core 2 0 2018-01-08 15:55:20.692
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY org.eclipse.cdt.dsf 4 10005 2018-01-08 15:55:22.052
!MESSAGE Request for monitor: 'CountingRequestMonitor: Status ERROR: org.eclipse.cdt.dsf code=0  null children=[Status ERROR: org.eclipse.cdt.debug.edc code=0 Fail to get TCF context for process: rc.root.000440059131 java.lang.Exception: java.lang.Error: Channel is closed]' resulted in an error.
!SUBENTRY 1 org.eclipse.cdt.debug.edc 4 0 2018-01-08 15:55:22.052
!MESSAGE Fail to get TCF context for process: rc.root.000440059131
!STACK 0
java.lang.Exception: java.lang.Error: Channel is closed
	at org.eclipse.tcf.core.Command.<init>(Command.java:83)
	at org.eclipse.tcf.internal.services.remote.ProcessesProxy$3.<init>(ProcessesProxy.java:165)
	at org.eclipse.tcf.internal.services.remote.ProcessesProxy.getContext(ProcessesProxy.java:165)
	at org.eclipse.cdt.debug.edc.internal.services.dsf.Processes$2.run(Processes.java:221)
	at org.eclipse.tcf.EventQueue.run(EventQueue.java:95)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Error: Channel is closed
	at org.eclipse.tcf.core.AbstractChannel.sendCommand(AbstractChannel.java:875)
	at org.eclipse.tcf.core.Command.<init>(Command.java:79)
	... 5 more

!ENTRY com.silabs.ss.framework.debugger.tcf.agent 1 0 2018-01-08 16:18:37.608
!MESSAGE Launching SiAgent (Silicon Labs TCF Agent)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:18:42.122
!MESSAGE Failed to connect, verify on line, due to exception https://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:944)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:376)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:18:42.124
!MESSAGE Failed to connect, verify on line, due to exception http://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:959)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:376)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:18:42.129
!MESSAGE Failed to connect, verify on line, due to exception https://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:944)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.access$0(AssetService.java:935)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:325)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:18:42.132
!MESSAGE Failed to connect, verify on line, due to exception http://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:959)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.access$0(AssetService.java:935)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:325)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 1 0 2018-01-08 16:18:42.135
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
!STACK 0
java.lang.Exception: /efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json is not currently available offline.  Please make sure you have Internet access.
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:378)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 2 0 2018-01-08 16:18:42.137
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY com.silabs.ss.framework.debugger.core 4 0 2018-01-08 16:18:42.138
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Asset error while getting device descriptor(s) for agent
	at com.silabs.ss.platform.api.rcp.core.StatusReporter.newCoreException(StatusReporter.java:239)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:63)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	... 14 more
!SUBENTRY 1 com.silabs.ss.framework.debugger.tcf.agent 4 0 2018-01-08 16:18:42.138
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
!SUBENTRY 2 com.silabs.ss.platform.content.core 2 0 2018-01-08 16:18:42.138
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY org.eclipse.cdt.debug.edc 4 10005 2018-01-08 16:38:30.865
!MESSAGE Fail to read memory.
!STACK 0
org.eclipse.tcf.internal.services.remote.MemoryProxy$MemoryErrorReport: TCF command exception:
Command: Memory get "rc.root.000440059131.m.C.CODE", 0, 1, 72, 0
Exception: Invalid address
Error code: 17
	at org.eclipse.tcf.internal.services.remote.MemoryProxy$MemoryCommand.toMemoryError(MemoryProxy.java:379)
	at org.eclipse.tcf.internal.services.remote.MemoryProxy$MemContext$2.done(MemoryProxy.java:257)
	at org.eclipse.tcf.core.Command.result(Command.java:111)
	at org.eclipse.tcf.core.AbstractChannel.handleInput(AbstractChannel.java:997)
	at org.eclipse.tcf.core.AbstractChannel.access$0(AbstractChannel.java:943)
	at org.eclipse.tcf.core.AbstractChannel$1$1.run(AbstractChannel.java:293)
	at org.eclipse.tcf.EventQueue.run(EventQueue.java:95)
	at java.lang.Thread.run(Thread.java:745)

!ENTRY org.eclipse.cdt.debug.edc 4 10005 2018-01-08 16:38:30.980
!MESSAGE Fail to read memory.
!STACK 0
org.eclipse.tcf.internal.services.remote.MemoryProxy$MemoryErrorReport: TCF command exception:
Command: Memory get "rc.root.000440059131.m.C.CODE", 32, 1, 80, 0
Exception: Invalid address
Error code: 17
	at org.eclipse.tcf.internal.services.remote.MemoryProxy$MemoryCommand.toMemoryError(MemoryProxy.java:379)
	at org.eclipse.tcf.internal.services.remote.MemoryProxy$MemContext$2.done(MemoryProxy.java:257)
	at org.eclipse.tcf.core.Command.result(Command.java:111)
	at org.eclipse.tcf.core.AbstractChannel.handleInput(AbstractChannel.java:997)
	at org.eclipse.tcf.core.AbstractChannel.access$0(AbstractChannel.java:943)
	at org.eclipse.tcf.core.AbstractChannel$1$1.run(AbstractChannel.java:293)
	at org.eclipse.tcf.EventQueue.run(EventQueue.java:95)
	at java.lang.Thread.run(Thread.java:745)

!ENTRY org.eclipse.cdt.debug.edc 4 10005 2018-01-08 16:38:31.037
!MESSAGE Fail to read memory.
!STACK 0
org.eclipse.tcf.internal.services.remote.MemoryProxy$MemoryErrorReport: TCF command exception:
Command: Memory get "rc.root.000440059131.m.C.CODE", 64, 1, 80, 0
Exception: Invalid address
Error code: 17
	at org.eclipse.tcf.internal.services.remote.MemoryProxy$MemoryCommand.toMemoryError(MemoryProxy.java:379)
	at org.eclipse.tcf.internal.services.remote.MemoryProxy$MemContext$2.done(MemoryProxy.java:257)
	at org.eclipse.tcf.core.Command.result(Command.java:111)
	at org.eclipse.tcf.core.AbstractChannel.handleInput(AbstractChannel.java:997)
	at org.eclipse.tcf.core.AbstractChannel.access$0(AbstractChannel.java:943)
	at org.eclipse.tcf.core.AbstractChannel$1$1.run(AbstractChannel.java:293)
	at org.eclipse.tcf.EventQueue.run(EventQueue.java:95)
	at java.lang.Thread.run(Thread.java:745)

!ENTRY org.eclipse.cdt.debug.edc 4 10005 2018-01-08 16:38:31.117
!MESSAGE Fail to read memory.
!STACK 0
org.eclipse.tcf.internal.services.remote.MemoryProxy$MemoryErrorReport: TCF command exception:
Command: Memory get "rc.root.000440059131.m.C.CODE", 128, 1, 80, 0
Exception: Invalid address
Error code: 17
	at org.eclipse.tcf.internal.services.remote.MemoryProxy$MemoryCommand.toMemoryError(MemoryProxy.java:379)
	at org.eclipse.tcf.internal.services.remote.MemoryProxy$MemContext$2.done(MemoryProxy.java:257)
	at org.eclipse.tcf.core.Command.result(Command.java:111)
	at org.eclipse.tcf.core.AbstractChannel.handleInput(AbstractChannel.java:997)
	at org.eclipse.tcf.core.AbstractChannel.access$0(AbstractChannel.java:943)
	at org.eclipse.tcf.core.AbstractChannel$1$1.run(AbstractChannel.java:293)
	at org.eclipse.tcf.EventQueue.run(EventQueue.java:95)
	at java.lang.Thread.run(Thread.java:745)

!ENTRY org.eclipse.cdt.debug.edc 4 10005 2018-01-08 16:38:31.258
!MESSAGE Fail to read memory.
!STACK 0
org.eclipse.tcf.internal.services.remote.MemoryProxy$MemoryErrorReport: TCF command exception:
Command: Memory get "rc.root.000440059131.m.C.CODE", 160, 1, 80, 0
Exception: Invalid address
Error code: 17
	at org.eclipse.tcf.internal.services.remote.MemoryProxy$MemoryCommand.toMemoryError(MemoryProxy.java:379)
	at org.eclipse.tcf.internal.services.remote.MemoryProxy$MemContext$2.done(MemoryProxy.java:257)
	at org.eclipse.tcf.core.Command.result(Command.java:111)
	at org.eclipse.tcf.core.AbstractChannel.handleInput(AbstractChannel.java:997)
	at org.eclipse.tcf.core.AbstractChannel.access$0(AbstractChannel.java:943)
	at org.eclipse.tcf.core.AbstractChannel$1$1.run(AbstractChannel.java:293)
	at org.eclipse.tcf.EventQueue.run(EventQueue.java:95)
	at java.lang.Thread.run(Thread.java:745)

!ENTRY com.silabs.ss.framework.debugger.tcf.agent 1 0 2018-01-08 16:40:56.570
!MESSAGE Launching SiAgent (Silicon Labs TCF Agent)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:41:00.905
!MESSAGE Failed to connect, verify on line, due to exception https://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:944)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:376)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:41:00.907
!MESSAGE Failed to connect, verify on line, due to exception http://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:959)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:376)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:41:00.911
!MESSAGE Failed to connect, verify on line, due to exception https://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:944)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.access$0(AssetService.java:935)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:325)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:41:00.914
!MESSAGE Failed to connect, verify on line, due to exception http://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:959)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.access$0(AssetService.java:935)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:325)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 1 0 2018-01-08 16:41:00.916
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
!STACK 0
java.lang.Exception: /efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json is not currently available offline.  Please make sure you have Internet access.
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:378)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 2 0 2018-01-08 16:41:00.917
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY com.silabs.ss.framework.debugger.core 4 0 2018-01-08 16:41:00.919
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Asset error while getting device descriptor(s) for agent
	at com.silabs.ss.platform.api.rcp.core.StatusReporter.newCoreException(StatusReporter.java:239)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:63)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	... 14 more
!SUBENTRY 1 com.silabs.ss.framework.debugger.tcf.agent 4 0 2018-01-08 16:41:00.919
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
!SUBENTRY 2 com.silabs.ss.platform.content.core 2 0 2018-01-08 16:41:00.919
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY com.silabs.ss.framework.debugger.tcf.agent 1 0 2018-01-08 16:43:18.737
!MESSAGE Launching SiAgent (Silicon Labs TCF Agent)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:43:22.488
!MESSAGE Failed to connect, verify on line, due to exception https://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:944)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:376)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:43:22.491
!MESSAGE Failed to connect, verify on line, due to exception http://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:959)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:376)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:43:22.495
!MESSAGE Failed to connect, verify on line, due to exception https://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:944)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.access$0(AssetService.java:935)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:325)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:43:22.498
!MESSAGE Failed to connect, verify on line, due to exception http://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:959)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.access$0(AssetService.java:935)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:325)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 1 0 2018-01-08 16:43:22.500
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
!STACK 0
java.lang.Exception: /efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json is not currently available offline.  Please make sure you have Internet access.
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:378)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 2 0 2018-01-08 16:43:22.504
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY com.silabs.ss.framework.debugger.core 4 0 2018-01-08 16:43:22.508
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Asset error while getting device descriptor(s) for agent
	at com.silabs.ss.platform.api.rcp.core.StatusReporter.newCoreException(StatusReporter.java:239)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:63)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	... 14 more
!SUBENTRY 1 com.silabs.ss.framework.debugger.tcf.agent 4 0 2018-01-08 16:43:22.509
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
!SUBENTRY 2 com.silabs.ss.platform.content.core 2 0 2018-01-08 16:43:22.509
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY com.silabs.ss.framework.debugger.tcf.agent 1 0 2018-01-08 16:44:56.681
!MESSAGE Launching SiAgent (Silicon Labs TCF Agent)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:45:00.420
!MESSAGE Failed to connect, verify on line, due to exception https://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:944)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:376)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:45:00.423
!MESSAGE Failed to connect, verify on line, due to exception http://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:959)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:376)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:45:00.428
!MESSAGE Failed to connect, verify on line, due to exception https://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:944)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.access$0(AssetService.java:935)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:325)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:45:00.430
!MESSAGE Failed to connect, verify on line, due to exception http://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:959)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.access$0(AssetService.java:935)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:325)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 1 0 2018-01-08 16:45:00.435
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
!STACK 0
java.lang.Exception: /efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json is not currently available offline.  Please make sure you have Internet access.
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:378)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 2 0 2018-01-08 16:45:00.437
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY com.silabs.ss.framework.debugger.core 4 0 2018-01-08 16:45:00.438
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Asset error while getting device descriptor(s) for agent
	at com.silabs.ss.platform.api.rcp.core.StatusReporter.newCoreException(StatusReporter.java:239)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:63)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	... 14 more
!SUBENTRY 1 com.silabs.ss.framework.debugger.tcf.agent 4 0 2018-01-08 16:45:00.439
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
!SUBENTRY 2 com.silabs.ss.platform.content.core 2 0 2018-01-08 16:45:00.439
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY com.silabs.ss.framework.debugger.tcf.agent 1 0 2018-01-08 16:45:57.269
!MESSAGE Launching SiAgent (Silicon Labs TCF Agent)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:46:02.013
!MESSAGE Failed to connect, verify on line, due to exception https://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:944)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:376)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:46:02.016
!MESSAGE Failed to connect, verify on line, due to exception http://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:959)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:376)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:46:02.024
!MESSAGE Failed to connect, verify on line, due to exception https://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:944)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.access$0(AssetService.java:935)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:325)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:46:02.027
!MESSAGE Failed to connect, verify on line, due to exception http://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:959)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.access$0(AssetService.java:935)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:325)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 1 0 2018-01-08 16:46:02.088
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
!STACK 0
java.lang.Exception: /efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json is not currently available offline.  Please make sure you have Internet access.
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:378)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.framework.debugger.core 4 0 2018-01-08 16:46:02.089
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Asset error while getting device descriptor(s) for agent
	at com.silabs.ss.platform.api.rcp.core.StatusReporter.newCoreException(StatusReporter.java:239)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:63)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	... 14 more
!SUBENTRY 1 com.silabs.ss.framework.debugger.tcf.agent 4 0 2018-01-08 16:46:02.090
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
!SUBENTRY 2 com.silabs.ss.platform.content.core 2 0 2018-01-08 16:46:02.090
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY com.silabs.ss.platform.content.core 2 0 2018-01-08 16:46:02.094
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY com.silabs.ss.framework.debugger.tcf.agent 1 0 2018-01-08 16:47:15.909
!MESSAGE Launching SiAgent (Silicon Labs TCF Agent)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:47:19.668
!MESSAGE Failed to connect, verify on line, due to exception https://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:944)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:376)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:47:19.673
!MESSAGE Failed to connect, verify on line, due to exception http://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:959)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:376)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:47:19.678
!MESSAGE Failed to connect, verify on line, due to exception https://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:944)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.access$0(AssetService.java:935)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:325)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:47:19.682
!MESSAGE Failed to connect, verify on line, due to exception http://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:959)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.access$0(AssetService.java:935)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:325)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 1 0 2018-01-08 16:47:19.685
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
!STACK 0
java.lang.Exception: /efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json is not currently available offline.  Please make sure you have Internet access.
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:378)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 2 0 2018-01-08 16:47:19.687
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY com.silabs.ss.framework.debugger.core 4 0 2018-01-08 16:47:19.688
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Asset error while getting device descriptor(s) for agent
	at com.silabs.ss.platform.api.rcp.core.StatusReporter.newCoreException(StatusReporter.java:239)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:63)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	... 14 more
!SUBENTRY 1 com.silabs.ss.framework.debugger.tcf.agent 4 0 2018-01-08 16:47:19.688
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
!SUBENTRY 2 com.silabs.ss.platform.content.core 2 0 2018-01-08 16:47:19.688
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY com.silabs.ss.framework.debugger.tcf.agent 1 0 2018-01-08 16:48:13.142
!MESSAGE Launching SiAgent (Silicon Labs TCF Agent)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:48:17.008
!MESSAGE Failed to connect, verify on line, due to exception https://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:944)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:376)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:48:17.010
!MESSAGE Failed to connect, verify on line, due to exception http://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:959)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:376)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:48:17.031
!MESSAGE Failed to connect, verify on line, due to exception https://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:944)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.access$0(AssetService.java:935)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:325)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:48:17.033
!MESSAGE Failed to connect, verify on line, due to exception http://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:959)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.access$0(AssetService.java:935)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:325)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 1 0 2018-01-08 16:48:17.034
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
!STACK 0
java.lang.Exception: /efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json is not currently available offline.  Please make sure you have Internet access.
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:378)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 2 0 2018-01-08 16:48:17.036
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY com.silabs.ss.framework.debugger.core 4 0 2018-01-08 16:48:17.036
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Asset error while getting device descriptor(s) for agent
	at com.silabs.ss.platform.api.rcp.core.StatusReporter.newCoreException(StatusReporter.java:239)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:63)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	... 14 more
!SUBENTRY 1 com.silabs.ss.framework.debugger.tcf.agent 4 0 2018-01-08 16:48:17.037
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
!SUBENTRY 2 com.silabs.ss.platform.content.core 2 0 2018-01-08 16:48:17.037
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY com.silabs.ss.framework.debugger.tcf.agent 1 0 2018-01-08 16:52:01.262
!MESSAGE Launching SiAgent (Silicon Labs TCF Agent)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:52:05.039
!MESSAGE Failed to connect, verify on line, due to exception https://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:944)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:376)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:52:05.041
!MESSAGE Failed to connect, verify on line, due to exception http://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:959)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:376)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:52:05.046
!MESSAGE Failed to connect, verify on line, due to exception https://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:944)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.access$0(AssetService.java:935)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:325)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:52:05.049
!MESSAGE Failed to connect, verify on line, due to exception http://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:959)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.access$0(AssetService.java:935)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:325)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 1 0 2018-01-08 16:52:05.052
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
!STACK 0
java.lang.Exception: /efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json is not currently available offline.  Please make sure you have Internet access.
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:378)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 2 0 2018-01-08 16:52:05.054
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY com.silabs.ss.framework.debugger.core 4 0 2018-01-08 16:52:05.055
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Asset error while getting device descriptor(s) for agent
	at com.silabs.ss.platform.api.rcp.core.StatusReporter.newCoreException(StatusReporter.java:239)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:63)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	... 14 more
!SUBENTRY 1 com.silabs.ss.framework.debugger.tcf.agent 4 0 2018-01-08 16:52:05.059
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
!SUBENTRY 2 com.silabs.ss.platform.content.core 2 0 2018-01-08 16:52:05.060
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY com.silabs.ss.framework.debugger.tcf.agent 1 0 2018-01-08 16:52:16.301
!MESSAGE Launching SiAgent (Silicon Labs TCF Agent)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:52:20.154
!MESSAGE Failed to connect, verify on line, due to exception https://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:944)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:376)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:52:20.156
!MESSAGE Failed to connect, verify on line, due to exception http://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:959)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:376)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:52:20.163
!MESSAGE Failed to connect, verify on line, due to exception https://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:944)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.access$0(AssetService.java:935)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:325)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:52:20.165
!MESSAGE Failed to connect, verify on line, due to exception http://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:959)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.access$0(AssetService.java:935)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:325)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 1 0 2018-01-08 16:52:20.167
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
!STACK 0
java.lang.Exception: /efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json is not currently available offline.  Please make sure you have Internet access.
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:378)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 2 0 2018-01-08 16:52:20.168
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY com.silabs.ss.framework.debugger.core 4 0 2018-01-08 16:52:20.169
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Asset error while getting device descriptor(s) for agent
	at com.silabs.ss.platform.api.rcp.core.StatusReporter.newCoreException(StatusReporter.java:239)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:63)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	... 14 more
!SUBENTRY 1 com.silabs.ss.framework.debugger.tcf.agent 4 0 2018-01-08 16:52:20.169
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
!SUBENTRY 2 com.silabs.ss.platform.content.core 2 0 2018-01-08 16:52:20.169
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY com.silabs.ss.framework.debugger.tcf.agent 1 0 2018-01-08 16:53:46.408
!MESSAGE Launching SiAgent (Silicon Labs TCF Agent)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:53:50.239
!MESSAGE Failed to connect, verify on line, due to exception https://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:944)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:376)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:53:50.241
!MESSAGE Failed to connect, verify on line, due to exception http://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:959)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:376)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:53:50.247
!MESSAGE Failed to connect, verify on line, due to exception https://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:944)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.access$0(AssetService.java:935)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:325)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 4 0 2018-01-08 16:53:50.250
!MESSAGE Failed to connect, verify on line, due to exception http://developer.silabs.com/studio/v4/assets/
!STACK 0
java.net.UnknownHostException: developer.silabs.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.online(AssetService.java:959)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.access$0(AssetService.java:935)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:325)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.platform.content.core 1 0 2018-01-08 16:53:50.252
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
!STACK 0
java.lang.Exception: /efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json is not currently available offline.  Please make sure you have Internet access.
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:378)
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService$2.run(AssetService.java:323)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.silabs.ss.framework.debugger.core 4 0 2018-01-08 16:53:50.254
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Asset error while getting device descriptor(s) for agent
	at com.silabs.ss.platform.api.rcp.core.StatusReporter.newCoreException(StatusReporter.java:239)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:63)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	... 14 more
!SUBENTRY 1 com.silabs.ss.framework.debugger.tcf.agent 4 0 2018-01-08 16:53:50.254
!MESSAGE Asset error while getting device descriptor(s) for agent
!STACK 1
org.eclipse.core.runtime.CoreException: Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json
	at com.silabs.ss.platform.internal.api.content.core.asset.AssetService.resolveAsset(AssetService.java:340)
	at com.silabs.ss.framework.debugger.api.tcf.agent.SiAgentUtils.resolveDeviceDescriptors(SiAgentUtils.java:49)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence.ensurePartDescriptor(SLSLaunchSequence.java:640)
	at com.silabs.ss.framework.debugger.api.core.SLSLaunchSequence$2.execute(SLSLaunchSequence.java:100)
	at org.eclipse.cdt.dsf.concurrent.Sequence.executeStep(Sequence.java:459)
	at org.eclipse.cdt.dsf.concurrent.Sequence.access$2(Sequence.java:373)
	at org.eclipse.cdt.dsf.concurrent.Sequence$2.handleSuccess(Sequence.java:420)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.handleCompleted(RequestMonitor.java:385)
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor$2.run(RequestMonitor.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
!SUBENTRY 2 com.silabs.ss.platform.content.core 2 0 2018-01-08 16:53:50.254
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY com.silabs.ss.platform.content.core 2 0 2018-01-08 16:53:50.258
!MESSAGE Unable to download asset://efm8/debug/lb1/EFM8LB1_B/EFM8LB12F64E-B-QFN32_debug.json

!ENTRY com.silabs.ss.framework.debugger.tcf.core 4 0 2018-01-08 16:54:41.932
!MESSAGE TCF task failed
!STACK 0
java.io.IOException: Command [C 9248 DebugAdapter disconnect "root.000440059131"] aborted
	at org.eclipse.tcf.core.AbstractChannel$9.run(AbstractChannel.java:753)
	at org.eclipse.tcf.EventQueue.run(EventQueue.java:95)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.eclipse.tcf.core.ChannelTCP.get(ChannelTCP.java:162)
	at org.eclipse.tcf.core.StreamChannel.read(StreamChannel.java:84)
	at org.eclipse.tcf.core.AbstractChannel$1.run(AbstractChannel.java:254)

!ENTRY org.eclipse.tcf 4 0 2018-01-08 16:54:41.936
!MESSAGE Cannot close channel streams
!STACK 0
java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at org.eclipse.tcf.core.ChannelTCP.stop(ChannelTCP.java:200)
	at org.eclipse.tcf.core.AbstractChannel$8.run(AbstractChannel.java:716)

!ENTRY com.silabs.ss.framework.debugger.tcf.agent 4 0 2018-01-08 16:54:41.939
!MESSAGE Lost connection to agent
!STACK 0
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.eclipse.tcf.core.ChannelTCP.get(ChannelTCP.java:162)
	at org.eclipse.tcf.core.StreamChannel.read(StreamChannel.java:84)
	at org.eclipse.tcf.core.AbstractChannel$1.run(AbstractChannel.java:254)

!ENTRY org.eclipse.cdt.dsf 4 -1 2018-01-08 16:54:41.970
!MESSAGE Invocation exception when calling a service event handler method
!STACK 0
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor240.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.cdt.dsf.service.DsfSession.doDispatchEvent(DsfSession.java:531)
	at org.eclipse.cdt.dsf.service.DsfSession.access$2(DsfSession.java:475)
	at org.eclipse.cdt.dsf.service.DsfSession$3.run(DsfSession.java:398)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.RejectedExecutionException: Display org.eclipse.swt.widgets.Display@1feb1ef is disposed
	at org.eclipse.cdt.dsf.ui.concurrent.SimpleDisplayExecutor.execute(SimpleDisplayExecutor.java:85)
	at org.eclipse.cdt.dsf.ui.viewmodel.AbstractVMAdapter.handleEvent(AbstractVMAdapter.java:260)
	at org.eclipse.cdt.dsf.ui.viewmodel.datamodel.AbstractDMVMAdapter.eventDispatched(AbstractDMVMAdapter.java:103)
	... 13 more
Caused by: org.eclipse.swt.SWTException: Device is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.SWT.error(SWT.java:4377)
	at org.eclipse.swt.widgets.Display.error(Display.java:1258)
	at org.eclipse.swt.widgets.Display.asyncExec(Display.java:709)
	at org.eclipse.cdt.dsf.ui.concurrent.SimpleDisplayExecutor.execute(SimpleDisplayExecutor.java:77)
	... 15 more
Root exception:
java.util.concurrent.RejectedExecutionException: Display org.eclipse.swt.widgets.Display@1feb1ef is disposed
	at org.eclipse.cdt.dsf.ui.concurrent.SimpleDisplayExecutor.execute(SimpleDisplayExecutor.java:85)
	at org.eclipse.cdt.dsf.ui.viewmodel.AbstractVMAdapter.handleEvent(AbstractVMAdapter.java:260)
	at org.eclipse.cdt.dsf.ui.viewmodel.datamodel.AbstractDMVMAdapter.eventDispatched(AbstractDMVMAdapter.java:103)
	at sun.reflect.GeneratedMethodAccessor240.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.cdt.dsf.service.DsfSession.doDispatchEvent(DsfSession.java:531)
	at org.eclipse.cdt.dsf.service.DsfSession.access$2(DsfSession.java:475)
	at org.eclipse.cdt.dsf.service.DsfSession$3.run(DsfSession.java:398)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.swt.SWTException: Device is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.SWT.error(SWT.java:4377)
	at org.eclipse.swt.widgets.Display.error(Display.java:1258)
	at org.eclipse.swt.widgets.Display.asyncExec(Display.java:709)
	at org.eclipse.cdt.dsf.ui.concurrent.SimpleDisplayExecutor.execute(SimpleDisplayExecutor.java:77)
	... 15 more
